apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-10-11
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-10-11
    app.kubernetes.io/part-of: demo-10-11
  name: demo-10-11
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: demo-10-11
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: demo-10-11
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jsese-tenant/demo-10-11/demo-10-11@sha256:4d43b163eca6fd9d3686dab45d9f925cefad287f0e332257a3c28c35c6ca8830
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
