apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: demo-10-11
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jsese-tenant/demo-10-11/demo-10-11@sha256:d4772f2649d26a66a8b16fff6956827fbd6dee7f07440f00c553d0f864808006
        name: my-java-springboot
        resources: {}
status: {}
